# Generated by Django 5.0.6 on 2024-07-19 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miapp', '0005_rename_fecha_nacimiento_userprofile_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='email',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='name',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='password1',
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='photo',
            field=models.FileField(blank=True, null=True, upload_to='certificados/'),
        ),
    ]
